name: flutter_admin_web
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  intl: ^0.17.0
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.15
  #flutter_inapp_purchase: ^5.1.2
  rxdart: ^0.26.0
  logger: ^1.1.0
  equatable: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.0.2+1
  dio: ^4.0.6
  # smooth_star_rating: ^1.1.1
  #flutter_screenutil: ^5.0.1+2
  flutter_screenutil: ^5.5.3+2
  flutter_spinkit: ^5.1.0
  #flutter_facebook_login: ^3.0.0

  firebase_auth: ^3.4.1
  cloud_firestore: ^3.2.1
  firebase_core: ^1.19.1
  firebase_messaging: ^11.4.4
  google_sign_in: ^5.3.3

  fluttertoast: ^8.0.9
  path_provider: ^2.0.11
  archive: ^3.3.0
  flutter_archive: ^5.0.0
  flutter_downloader: ^1.8.0+1
  uuid: ^3.0.6
  scrollable_positioned_list: ^0.2.3
  cached_network_image: ^3.2.1
  url_launcher: ^6.1.4
  qr_flutter: ^4.0.0
  share: ^2.0.4
  image_picker: ^0.8.5+3
  # ^0.8.4+4
  flutter_html: ^2.2.1
  #  webview_flutter: ^2.0.4
  adaptive_dialog: ^1.6.4+1
  add_2_calendar: ^2.1.3
  table_calendar: ^3.0.6
  # webview_flutter_plus: ^0.1.1+9
  # xml_parser: ^0.1.2
  xml: ^5.4.1
  xml2json: ^5.3.2
  permission_handler: ^8.3.0
  native_pdf_view: ^6.0.0+1
  http: ^0.13.4
  video_player: ^2.4.5
  flick_video_player: ^0.5.0
  #chewie: ^1.2.2
  open_file: ^3.2.1
  #flutter_filereader: ^2.1.0
  flutter_inappwebview: ^5.4.3+7
  #  flutter_webview_plugin: ^0.4.0
  font_awesome_flutter: ^9.2.0
  flutter_svg: ^0.22.0
  extended_nested_scroll_view: ^5.1.3
  #  connectivity: ^3.0.6
  connectivity_plus: ^2.3.5
  flutter_breadcrumb: ^1.0.1
  syncfusion_flutter_calendar: ^19.4.56
  month_picker_dialog: ^0.4.0
  scroll_to_index: ^2.1.1
  #  html_editor:
  #    path: ../flutter-html-editor-master
  # Upendra added

  # Upendra
  file_picker: ^4.6.1
  #unicorndial: ^1.1.5
  in_app_purchase: ^3.0.6
  provider: ^6.0.3

  #  Vinoth
  #smart_select: ^4.3.2
  simple_animations: ^4.2.0
  #  signalr_client:
  #  signalr_flutter: ^0.1.0
  flutter_slidable: ^1.3.0
  simple_url_preview: ^3.0.1
  timeago: ^3.2.2
  #  firebase_database:

  #Aman
  flutter_launcher_icons: ^0.9.3
  syncfusion_flutter_charts: ^19.4.56

  #  firebase_analytics: ^7.0.1
  device_info: ^2.0.3
  flutter_local_notifications: ^9.6.1

  flutter_localizations:
    sdk: flutter
  smooth_star_rating_null_safety: ^1.0.4+2
  json_annotation: ^4.5.0
  top_snackbar_flutter: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator: ^1.1.3
  json_serializable: ^6.2.0

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 600
  #          weight: 700
  assets:
    - assets/
    - assets/js/
    - assets/images/
    - lang/localization_en.json
    - lang/localization_ar.json