import 'package:flutter_admin_web/generated/json/base/json_convert_content.dart';

class DummyMyLearnPlusResponseEntity
    with JsonConvert<DummyMyLearnPlusResponseEntity> {
  List<DummyMyLearnPlusResponseTable> CourseList2 = [];
  List<DummyMyLearnPlusCatelgoResponse> CourseList = [];
}

class DummyMyLearnPlusResponseTable
    with JsonConvert<DummyMyLearnPlusResponseTable> {
  int totalrecordscount = 0;
}

class DummyMyLearnPlusCatelgoResponse
    with JsonConvert<DummyMyLearnPlusCatelgoResponse> {
  String expired = "";
  int attemptsLeft = 0;
  String contentStatus = "";
  String reportLink = "";
  String discussionsLink = "";
  String certificateLink = "";
  String notesLink = "";
  String cancelEventLink = "";
  String downLoadLink = "";
  String repurchaseLink = "";
  String setcompleteLink = "";
  String viewRecordingLink = "";
  String instructorCommentsLink = "";
  int required = 0;
  String downloadCalender = "";
  String eventScheduleLink = "";
  String eventScheduleStatus = "";
  String eventScheduleConfirmLink = "";
  String eventScheduleCancelLink = "";
  String eventScheduleReserveTime = "";
  String eventScheduleReserveStatus = "";
  String reScheduleEvent = "";
  String addorremoveattendees = "";
  String cancelScheduleEvent = "";
  String sharelink = "";
  String surveyLink = "";
  String removeLink = "";
  String ratingLink = "";
  dynamic durationEndDate;
  String practiceAssessmentsAction = "";
  String createAssessmentAction = "";
  String overallProgressReportAction = "";
  String editLink = "";
  String titleName = "";
  int percentCompleted = 0;
  String percentCompletedClass = "";
  String windowProperties = "";
  String cancelOrderData = "";
  bool combinedTransaction = false;
  int eventScheduleType = 0;
  int typeofEvent = 0;
  String duration = "";
  bool isViewReview = false;
  String jwVideoKey = "";
  String credits = "";
  bool isArchived = false;
  String detailspopupTags = "";
  dynamic thumbnailIconPath;
  String instanceEventEnroll = "";
  String modules = "";
  String instanceEventReSchedule = "";
  String instanceEventReclass = "";
  String isEnrollFutureInstance = "";
  String reEnrollmentHistory = "";
  String isBadCancellationEnabled = "";
  int mediaTypeId = 0;
  String actionViewQRcode = "";
  dynamic recordingDetails;
  dynamic enrollmentLimit;
  dynamic availableSeats;
  dynamic noofUsersEnrolled;
  dynamic waitListLimit;
  dynamic waitListEnrolls;
  bool isBookingOpened = false;
  bool subSiteMemberShipExpiried = false;
  bool showLearnerActions = false;
  String skinId = "";
  String backGroundColor = "";
  String fontColor = "";
  int filterId = 0;
  int siteId = 0;
  int userSiteId = 0;
  String siteName = "";
  int contentTypeId = 0;
  String contentId = "";
  String title = "";
  dynamic totalRatings;
  String ratingId = "";
  String shortDescription = "";
  String thumbnailImagePath = "";
  dynamic instanceParentContentId;
  dynamic imageWithLink;
  String authorWithLink = "";
  dynamic eventStartDateTime;
  dynamic eventEndDateTime;
  dynamic eventStartDateTimeWithoutConvert;
  dynamic eventEndDateTimeTimeWithoutConvert;
  dynamic expandiconpath;
  String authorDisplayName = "";
  String contentType = "";
  dynamic createdOn;
  dynamic timeZone;
  dynamic tags;
  dynamic salePrice;
  dynamic currency;
  String viewLink = "";
  String detailsLink = "";
  String relatedContentLink = "";
  String viewSessionsLink = "";
  String suggesttoConnLink = "";
  String suggestwithFriendLink = "";
  dynamic sharetoRecommendedLink;
  dynamic isCoursePackage;
  String isRelatedcontent = "";
  dynamic isaddtomylearninglogo;
  dynamic locationName;
  String buildingName = "";
  dynamic joinUrl;
  String categorycolor = "";
  dynamic invitationUrl;
  String headerLocationName = "";
  dynamic subSiteUserId;
  String presenterDisplayName = "";
  dynamic presenterWithLink;
  bool showMembershipExpiryAlert = false;
  String authorName = "";
  dynamic freePrice;
  int siteUserId = 0;
  int scoId = 0;
  dynamic buyNowLink;
  bool bit5 = false;
  bool bit4 = false;
  bool openNewBrowserWindow = false;
  String salepricestrikeoff = "";
  dynamic creditScoreWithCreditTypes;
  dynamic creditScoreFirstPrefix;
  int eventType = 0;
  String instanceEventReclassStatus = "";
  String expiredContentExpiryDate = "";
  String expiredContentAvailableUntill = "";
  dynamic gradient1;
  dynamic gradient2;
  dynamic gradientColor;
  String shareContentwithUser = "";
}
