// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmLZF_hQ_YZPK81xK5duPt-j8eaDIgs-k',
    appId: '1:639139368781:web:2236bbfe2020e38f447104',
    messagingSenderId: '639139368781',
    projectId: 'instancy-f241d',
    authDomain: 'instancy-f241d.firebaseapp.com',
    databaseURL: 'https://instancy-f241d.firebaseio.com',
    storageBucket: 'instancy-f241d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXactZUQK_Y9YokmTt1Z-1VtnXJlHQOPU',
    appId: '1:639139368781:android:d31486198c38d533447104',
    messagingSenderId: '639139368781',
    projectId: 'instancy-f241d',
    databaseURL: 'https://instancy-f241d.firebaseio.com',
    storageBucket: 'instancy-f241d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcYZaS5FyBcrT4L1D79aySAAMooT9Y4ww',
    appId: '1:639139368781:ios:18b8dd14d2e989d6447104',
    messagingSenderId: '639139368781',
    projectId: 'instancy-f241d',
    databaseURL: 'https://instancy-f241d.firebaseio.com',
    storageBucket: 'instancy-f241d.appspot.com',
    androidClientId: '639139368781-5nptlij2nfuj915bu7rmqts7cc8ttjp2.apps.googleusercontent.com',
    iosClientId: '639139368781-1vvpqgi0gjgigh8341duhaev0gqd6c48.apps.googleusercontent.com',
    iosBundleId: 'com.instancy.instancyLearningMarket.Notification',
  );
}
